-- 아기의 기록 + 아기의 밥상 공유 스키마 (Postgres / Supabase)
-- MySQL(VIBE_BABY) → Postgres 포팅. 실행: Supabase SQL Editor 또는 psql.
-- 규칙: AUTO_INCREMENT→IDENTITY, tinyint(1)→smallint(0/1 유지), enum→text+CHECK, json→jsonb,
--       timestamp→timestamptz, ON UPDATE→트리거.

-- ── updated_at 자동 갱신 트리거 함수 ─────────────────────────
CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$
BEGIN NEW.updated_at = now(); RETURN NEW; END;
$$ LANGUAGE plpgsql;

-- ── users ───────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS users (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email       varchar(255) NOT NULL UNIQUE,
  name        varchar(255),
  provider    text NOT NULL CHECK (provider IN ('google','naver','kakao')),
  provider_id varchar(255) NOT NULL,
  created_at  timestamptz DEFAULT now(),
  plan        text NOT NULL DEFAULT 'premium' CHECK (plan IN ('free','premium')),
  UNIQUE (provider, provider_id)
);

-- ── babies ──────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS babies (
  id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       varchar(100) NOT NULL,
  birth_date date NOT NULL,
  gender     text NOT NULL CHECK (gender IN ('boy','girl')),
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  user_id    integer,
  share_code varchar(8) UNIQUE
);
CREATE INDEX IF NOT EXISTS idx_babies_user ON babies(user_id);
DROP TRIGGER IF EXISTS trg_babies_updated ON babies;
CREATE TRIGGER trg_babies_updated BEFORE UPDATE ON babies FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ── baby_users (공동 양육자 연결) ───────────────────────────
CREATE TABLE IF NOT EXISTS baby_users (
  baby_id integer NOT NULL,
  user_id integer NOT NULL,
  PRIMARY KEY (baby_id, user_id)
);

-- ── logs (활동: 수면/수유/배변 등) ──────────────────────────
CREATE TABLE IF NOT EXISTS logs (
  id         varchar(20) PRIMARY KEY,
  baby_id    integer NOT NULL REFERENCES babies(id) ON DELETE CASCADE,
  type       text NOT NULL CHECK (type IN ('sleep','feed','pee','poop','cry','walk','play','bath','solid')),
  log_date   date NOT NULL,
  start_time time,
  end_time   time,
  log_time   time,
  amount     smallint,
  feed_type  varchar(20),
  color      varchar(30),
  reason     varchar(50),
  note       text,
  created_at timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_logs_baby_date ON logs(baby_id, log_date);

-- ── todos ───────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS todos (
  id         varchar(20) PRIMARY KEY,
  baby_id    integer NOT NULL REFERENCES babies(id) ON DELETE CASCADE,
  text       text NOT NULL,
  category   text NOT NULL DEFAULT 'other' CHECK (category IN ('vaccine','feeding','play','supplies','other')),
  completed  smallint NOT NULL DEFAULT 0,
  created_at bigint NOT NULL,
  todo_date  date
);
CREATE INDEX IF NOT EXISTS idx_todos_baby ON todos(baby_id);

-- ── health_logs ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS health_logs (
  id         varchar(20) PRIMARY KEY,
  baby_id    integer NOT NULL REFERENCES babies(id) ON DELETE CASCADE,
  type       text NOT NULL CHECK (type IN ('temp','rash','symptom','other')),
  detail     text NOT NULL,
  log_date   date NOT NULL,
  log_time   time NOT NULL,
  created_at timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_health_baby ON health_logs(baby_id);

-- ── medications ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS medications (
  id              varchar(20) PRIMARY KEY,
  baby_id         integer NOT NULL REFERENCES babies(id) ON DELETE CASCADE,
  name            varchar(200) NOT NULL,
  dose            varchar(100),
  freq            varchar(100),
  note            text,
  prescribed_date date,
  created_at      timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_med_baby ON medications(baby_id);

-- ── developments (발달 마일스톤) ────────────────────────────
CREATE TABLE IF NOT EXISTS developments (
  baby_id      integer NOT NULL REFERENCES babies(id) ON DELETE CASCADE,
  milestone_id varchar(50) NOT NULL,
  completed    smallint NOT NULL DEFAULT 0,
  updated_at   timestamptz DEFAULT now(),
  PRIMARY KEY (baby_id, milestone_id)
);
DROP TRIGGER IF EXISTS trg_dev_updated ON developments;
CREATE TRIGGER trg_dev_updated BEFORE UPDATE ON developments FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ── growth_records ──────────────────────────────────────────
CREATE TABLE IF NOT EXISTS growth_records (
  id          varchar(20) PRIMARY KEY,
  baby_id     integer NOT NULL REFERENCES babies(id) ON DELETE CASCADE,
  record_date date NOT NULL,
  height      numeric(5,1),
  weight      numeric(5,2),
  created_at  timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_growth_baby ON growth_records(baby_id);

-- ── dev_memos ───────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS dev_memos (
  id         varchar(36) PRIMARY KEY,
  baby_id    integer NOT NULL,
  memo_date  date NOT NULL,
  text       text NOT NULL,
  created_at bigint NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_devmemos_baby ON dev_memos(baby_id);

-- ═══════════════ 아기의 밥상 전용 테이블 ═══════════════════
CREATE TABLE IF NOT EXISTS pantry_items (
  id             varchar(36) PRIMARY KEY,
  user_id        integer NOT NULL,
  kind           text NOT NULL DEFAULT 'ingredient' CHECK (kind IN ('ingredient','cube','prepared')),
  name           varchar(100) NOT NULL,
  category       varchar(40),
  storage        text NOT NULL DEFAULT 'fridge' CHECK (storage IN ('room','fridge','freezer')),
  quantity       numeric(8,2),
  unit           varchar(20),
  cube_count     integer,
  cube_volume_ml integer,
  cube_unit      varchar(4) DEFAULT 'ml',
  recipe_ref     varchar(36),
  purchase_date  date,
  open_date      date,
  cooked_date    date,
  expiry_date    date,
  for_baby_id    integer,
  note           text,
  created_at     bigint,
  updated_at     timestamptz DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_pantry_user ON pantry_items(user_id);
DROP TRIGGER IF EXISTS trg_pantry_updated ON pantry_items;
CREATE TRIGGER trg_pantry_updated BEFORE UPDATE ON pantry_items FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE IF NOT EXISTS meal_logs (
  id                  varchar(36) PRIMARY KEY,
  baby_id             integer NOT NULL,
  log_date            date NOT NULL,
  log_time            time,
  menu_name           varchar(120),
  recipe_ref          varchar(36),
  intake_ratio        text CHECK (intake_ratio IN ('all','half','little','refused')),
  estimated_intake_g  integer,
  estimated_kcal      integer,
  reaction            text,
  adverse_flag        smallint DEFAULT 0,
  adverse_note        text,
  is_new_ingredient   smallint DEFAULT 0,
  new_ingredient_name varchar(100),
  cubes_used          jsonb,
  note                text,
  before_amount_ml    integer,
  after_amount_ml     integer,
  created_at          bigint
);
CREATE INDEX IF NOT EXISTS idx_meallog_baby ON meal_logs(baby_id, log_date);

CREATE TABLE IF NOT EXISTS meal_photos (
  id          varchar(36) PRIMARY KEY,
  meal_log_id varchar(36),
  baby_id     integer NOT NULL,
  photo_stage text DEFAULT 'before' CHECK (photo_stage IN ('before','after')),
  image       text,
  thumb       text,
  taken_at    bigint
);
CREATE INDEX IF NOT EXISTS idx_photo_baby ON meal_photos(baby_id);
CREATE INDEX IF NOT EXISTS idx_photo_meallog ON meal_photos(meal_log_id);

CREATE TABLE IF NOT EXISTS saved_recipes (
  id          varchar(36) PRIMARY KEY,
  user_id     integer NOT NULL,
  title       varchar(160) NOT NULL,
  stage_tags  jsonb,
  ingredients jsonb,
  steps       jsonb,
  nutrition   jsonb,
  source_mode text CHECK (source_mode IN ('stock_only','buy_few','fresh_shop')),
  saved_at    bigint
);
CREATE INDEX IF NOT EXISTS idx_recipe_user ON saved_recipes(user_id);

CREATE TABLE IF NOT EXISTS meal_dev_checks (
  id           varchar(36) PRIMARY KEY,
  baby_id      integer NOT NULL,
  check_date   date NOT NULL,
  items        jsonb,
  judged_stage varchar(20),
  created_at   bigint
);
CREATE INDEX IF NOT EXISTS idx_devcheck_baby ON meal_dev_checks(baby_id);

CREATE TABLE IF NOT EXISTS assessments (
  id               varchar(36) PRIMARY KEY,
  baby_id          integer NOT NULL,
  week_of          date NOT NULL,
  intake_kcal_avg  integer,
  required_kcal    integer,
  adequacy_pct     integer,
  milk_solid_ratio varchar(20),
  llm_summary      text,
  created_at       bigint
);
CREATE INDEX IF NOT EXISTS idx_assess_baby ON assessments(baby_id);

-- 데이터 이전(명시적 id INSERT) 후 IDENTITY 시퀀스 보정:
--   SELECT setval(pg_get_serial_sequence('users','id'),  (SELECT COALESCE(MAX(id),1) FROM users));
--   SELECT setval(pg_get_serial_sequence('babies','id'), (SELECT COALESCE(MAX(id),1) FROM babies));
